CREATE TABLE TIPOS_COMBUSTIBLE (
	ID_COMBUSTIBLE SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE TIPOS_TRANSMISION (
	ID_TRANSMISION SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE CIUDADES (
	ID_CIUDAD SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE COLORES (
	ID_COLOR SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) UNIQUE NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE ETIQUETAS_AMBIENTALES (
	ID_ETIQUETA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(15) UNIQUE NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE CATEGORIAS (
	ID_CATEGORIA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) UNIQUE NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE MARCAS (
	ID_MARCA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) UNIQUE NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE 
);

CREATE TABLE MODELOS (
	ID_MODELO SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	MARCA_ID INT NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE,
	CONSTRAINT FK_MODELO_MARCA FOREIGN KEY (MARCA_ID) REFERENCES MARCAS (ID_MARCA)
);

CREATE TABLE VERSIONES (
	ID_VERSION SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	MODELO_ID INT NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE,
	CONSTRAINT FK_VERSION_MODELO FOREIGN KEY (MODELO_ID) REFERENCES MODELOS (ID_MODELO)
);

CREATE TABLE USUARIOS (
	ID_USUARIO SERIAL PRIMARY KEY,
	NOMBRES VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(50) NOT NULL,
	DNI VARCHAR(9) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	TELEFONO VARCHAR(15),
	TIPO_USUARIO VARCHAR(10) DEFAULT 'USER',
	ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE COCHES (
	ID_COCHE SERIAL PRIMARY KEY,
	ANIO_FABRICACION SMALLINT NOT NULL CHECK (ANIO_FABRICACION > 1900),
	KILOMETRAJE INT NOT NULL,
	PRECIO_VENTA DECIMAL(10, 2) NOT NULL,
	ESTADO VARCHAR(15) DEFAULT 'Disponible',
	FECHA_PUBLICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IMAGEN VARCHAR(255),
	VERSION_ID INT NOT NULL,
	COMBUSTIBLE_ID INT NOT NULL,
	TRANSMISION_ID INT NOT NULL,
	CIUDAD_ID INT NOT NULL,
	COLOR_ID INT NOT NULL,
	ETIQUETA_ID INT NOT NULL,
	CATEGORIA_ID INT NOT NULL,
	VENDEDOR_ID INT NOT NULL,
	
	CONSTRAINT FK_COCHE_VERSION FOREIGN KEY (VERSION_ID) REFERENCES VERSIONES (ID_VERSION),
	CONSTRAINT FK_COCHE_COMBUSTIBLE FOREIGN KEY (COMBUSTIBLE_ID) REFERENCES TIPOS_COMBUSTIBLE (ID_COMBUSTIBLE),
	CONSTRAINT FK_COCHE_TRANSMISION FOREIGN KEY (TRANSMISION_ID) REFERENCES TIPOS_TRANSMISION (ID_TRANSMISION),
	CONSTRAINT FK_COCHE_CIUDAD FOREIGN KEY (CIUDAD_ID) REFERENCES CIUDADES (ID_CIUDAD),
	CONSTRAINT FK_COCHE_COLOR FOREIGN KEY (COLOR_ID) REFERENCES COLORES (ID_COLOR),
	CONSTRAINT FK_COCHE_ETIQUETA FOREIGN KEY (ETIQUETA_ID) REFERENCES ETIQUETAS_AMBIENTALES (ID_ETIQUETA),
	CONSTRAINT FK_COCHE_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS (ID_CATEGORIA),
	CONSTRAINT FK_COCHE_VENDEDOR FOREIGN KEY (VENDEDOR_ID) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE TABLE FACTURAS (
	ID_FACTURA SERIAL PRIMARY KEY,
	COMPRADOR_ID INT NOT NULL,
	VENDEDOR_ID INT NOT NULL,
	TOTAL_BASE DECIMAL(10, 2) NOT NULL,
	IVA_IMPORTE DECIMAL(10, 2) DEFAULT 0.21,
	COMISION_PLATAFORMA DECIMAL(10, 2) DEFAULT 0.03,
	TOTAL_PAGADO DECIMAL(10, 2) NOT NULL,
	METODO_PAGO VARCHAR(20) DEFAULT 'TARJETA',
	CONTRATO_ACEPTADO BOOLEAN DEFAULT TRUE,
	FECHA_FACTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT FK_FACTURA_COMPRADOR FOREIGN KEY (COMPRADOR_ID) REFERENCES USUARIOS (ID_USUARIO),
	CONSTRAINT FK_FACTURA_VENDEDOR FOREIGN KEY (VENDEDOR_ID) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE TABLE LINEAS_FACTURA (
	ID_LINEA SERIAL PRIMARY KEY,
	FACTURA_ID INT NOT NULL,
	COCHE_ID INT NOT NULL,
	PRECIO_VENTA_MOMENTO DECIMAL(10, 2) NOT NULL,

	CONSTRAINT FK_LINEA_FACTURA FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS (ID_FACTURA),
	CONSTRAINT FK_LINEA_COCHE FOREIGN KEY (COCHE_ID) REFERENCES COCHES (ID_COCHE)
);

CREATE TABLE FAVORITOS (
	USUARIO_ID INT NOT NULL,
	COCHE_ID INT NOT NULL,
	FECHA_AGREGADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USUARIO_ID, COCHE_ID),
	CONSTRAINT FK_FAV_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID_USUARIO),
	CONSTRAINT FK_FAV_COCHE FOREIGN KEY (COCHE_ID) REFERENCES COCHES (ID_COCHE)
);